set tabstop=4       " Number of spaces that a <Tab> in the file counts for.
 
set shiftwidth=4    " Number of spaces to use for each step of (auto)indent.
 
set expandtab       " Use the appropriate number of spaces to insert a <Tab>.
                    " Spaces are used in indents with the '>' and '<' commands
                    " and when 'autoindent' is on. To insert a real tab when
                    " 'expandtab' is on, use CTRL-V <Tab>.
 
set smarttab        " When on, a <Tab> in front of a line inserts blanks
                    " according to 'shiftwidth'. 'tabstop' is used in other
                    " places. A <BS> will delete a 'shiftwidth' worth of space
                    " at the start of the line.

set number          " Show line numbers.

set showmatch       " When a bracket is inserted, briefly jump to the matching
                    " one. The jump is only done if the match can be seen on the
                    " screen. The time to show the match can be set with
                    " 'matchtime'.
set hlsearch        " When there is a previous search pattern, highlight all
                    " its matches.
 
set incsearch       " While typing a search command, show immediately where the
                    " so far typed pattern matches.
 
set ignorecase      " Ignore case in search patterns.
 
set smartcase       " Override the 'ignorecase' option if the search pattern
                    " contains upper case characters.

set autoindent      " Copy indent from current line when starting a new line
                    " (typing <CR> in Insert mode or when using the "o" or "O"
                    " command).
set copyindent    " copy the previous indentation on autoindenting
set smartindent

" set tabstop=4 shiftwidth=4 expandtab smarttab number showmatch hlsearch incsearch ignorecase smartcase autoindent copyindent smartindent pastetoggle=<F2> foldmethod=indent | colorscheme desert

set backspace=indent,eol,start  " allow backspacing over everything in insert mode
" set mouse=a         " Enable the use of the mouse.
" set paste
set diffopt+=iwhite
filetype plugin indent on
set shell=/bin/bash
syntax on

color desert
set cursorline
hi CursorLine cterm=NONE ctermbg=Green ctermfg=black
hi Search cterm=NONE ctermfg=red ctermbg=blue

au Filetype python set foldmethod=indent

set laststatus=2
set statusline=
set statusline+=%#PmenuSel#
set statusline+=%#LineNr#
set statusline+=\ %f
set statusline+=%m\
set statusline+=%=
set statusline+=%#CursorColumn#
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c
set statusline+=\ 

"" diff buffer and original file
map <F2> :w !diff % - <cr>
